// Comprehensive Queensland and Australian Suburbs & Postal Codes Directory

export interface SuburbData {
  suburb: string;
  state: string;
  postcode: string;
}

export const QUEENSLAND_SUBURBS: SuburbData[] = [
  // Brisbane Inner & City
  { suburb: "Brisbane City", state: "QLD", postcode: "4000" },
  { suburb: "Spring Hill", state: "QLD", postcode: "4000" },
  { suburb: "Petrie Terrace", state: "QLD", postcode: "4000" },
  { suburb: "Fortitude Valley", state: "QLD", postcode: "4006" },
  { suburb: "Bowen Hills", state: "QLD", postcode: "4006" },
  { suburb: "Newstead", state: "QLD", postcode: "4006" },
  { suburb: "Herston", state: "QLD", postcode: "4006" },
  { suburb: "New Farm", state: "QLD", postcode: "4005" },
  { suburb: "Teneriffe", state: "QLD", postcode: "4005" },
  { suburb: "South Brisbane", state: "QLD", postcode: "4101" },
  { suburb: "West End", state: "QLD", postcode: "4101" },
  { suburb: "Highgate Hill", state: "QLD", postcode: "4101" },
  { suburb: "Kangaroo Point", state: "QLD", postcode: "4169" },
  { suburb: "East Brisbane", state: "QLD", postcode: "4169" },
  { suburb: "Woolloongabba", state: "QLD", postcode: "4102" },
  { suburb: "Dutton Park", state: "QLD", postcode: "4102" },
  { suburb: "Annerley", state: "QLD", postcode: "4103" },
  { suburb: "Fairfield", state: "QLD", postcode: "4103" },
  { suburb: "Yeronga", state: "QLD", postcode: "4104" },
  { suburb: "Yeerongpilly", state: "QLD", postcode: "4105" },
  { suburb: "Moorooka", state: "QLD", postcode: "4105" },
  { suburb: "Tennyson", state: "QLD", postcode: "4105" },
  { suburb: "Rocklea", state: "QLD", postcode: "4106" },
  { suburb: "Salisbury", state: "QLD", postcode: "4107" },
  { suburb: "Archerfield", state: "QLD", postcode: "4108" },
  { suburb: "Coopers Plains", state: "QLD", postcode: "4108" },
  { suburb: "Acacia Ridge", state: "QLD", postcode: "4110" },
  { suburb: "Sunnybank", state: "QLD", postcode: "4109" },
  { suburb: "Sunnybank Hills", state: "QLD", postcode: "4109" },
  { suburb: "Robertson", state: "QLD", postcode: "4109" },
  { suburb: "Macgregor", state: "QLD", postcode: "4109" },
  { suburb: "Eight Mile Plains", state: "QLD", postcode: "4113" },
  { suburb: "Runcorn", state: "QLD", postcode: "4113" },
  { suburb: "Kuraby", state: "QLD", postcode: "4112" },
  { suburb: "Stretton", state: "QLD", postcode: "4116" },
  { suburb: "Calamvale", state: "QLD", postcode: "4116" },
  { suburb: "Drewvale", state: "QLD", postcode: "4116" },
  { suburb: "Parkinson", state: "QLD", postcode: "4115" },
  { suburb: "Algester", state: "QLD", postcode: "4115" },
  { suburb: "Mount Gravatt", state: "QLD", postcode: "4122" },
  { suburb: "Mount Gravatt East", state: "QLD", postcode: "4122" },
  { suburb: "Upper Mount Gravatt", state: "QLD", postcode: "4122" },
  { suburb: "Mansfield", state: "QLD", postcode: "4122" },
  { suburb: "Wishart", state: "QLD", postcode: "4122" },
  { suburb: "Holland Park", state: "QLD", postcode: "4121" },
  { suburb: "Holland Park West", state: "QLD", postcode: "4121" },
  { suburb: "Tarragindi", state: "QLD", postcode: "4121" },
  { suburb: "Greenslopes", state: "QLD", postcode: "4120" },
  { suburb: "Camp Hill", state: "QLD", postcode: "4152" },
  { suburb: "Carina", state: "QLD", postcode: "4152" },
  { suburb: "Carina Heights", state: "QLD", postcode: "4152" },
  { suburb: "Carindale", state: "QLD", postcode: "4152" },
  { suburb: "Cannon Hill", state: "QLD", postcode: "4170" },
  { suburb: "Morningside", state: "QLD", postcode: "4170" },
  { suburb: "Norman Park", state: "QLD", postcode: "4170" },
  { suburb: "Seven Hills", state: "QLD", postcode: "4170" },
  { suburb: "Bulimba", state: "QLD", postcode: "4171" },
  { suburb: "Hawthorne", state: "QLD", postcode: "4171" },
  { suburb: "Balmoral", state: "QLD", postcode: "4171" },
  { suburb: "Murarrie", state: "QLD", postcode: "4172" },
  { suburb: "Hemmant", state: "QLD", postcode: "4174" },
  { suburb: "Lytton", state: "QLD", postcode: "4178" },
  { suburb: "Wynnum", state: "QLD", postcode: "4178" },
  { suburb: "Wynnum West", state: "QLD", postcode: "4178" },
  { suburb: "Manly", state: "QLD", postcode: "4179" },
  { suburb: "Manly West", state: "QLD", postcode: "4179" },
  { suburb: "Lota", state: "QLD", postcode: "4179" },
  { suburb: "Tingalpa", state: "QLD", postcode: "4173" },
  { suburb: "Belmont", state: "QLD", postcode: "4153" },
  { suburb: "Chandler", state: "QLD", postcode: "4155" },
  { suburb: "Gumdale", state: "QLD", postcode: "4154" },
  { suburb: "Wakerley", state: "QLD", postcode: "4154" },

  // Brisbane North & North-West
  { suburb: "Milton", state: "QLD", postcode: "4064" },
  { suburb: "Paddington", state: "QLD", postcode: "4064" },
  { suburb: "Rosalie", state: "QLD", postcode: "4064" },
  { suburb: "Red Hill", state: "QLD", postcode: "4059" },
  { suburb: "Kelvin Grove", state: "QLD", postcode: "4059" },
  { suburb: "Ashgrove", state: "QLD", postcode: "4060" },
  { suburb: "Bardon", state: "QLD", postcode: "4065" },
  { suburb: "The Gap", state: "QLD", postcode: "4061" },
  { suburb: "Auchenflower", state: "QLD", postcode: "4066" },
  { suburb: "Toowong", state: "QLD", postcode: "4066" },
  { suburb: "St Lucia", state: "QLD", postcode: "4067" },
  { suburb: "Indooroopilly", state: "QLD", postcode: "4068" },
  { suburb: "Taringa", state: "QLD", postcode: "4068" },
  { suburb: "Chelmer", state: "QLD", postcode: "4068" },
  { suburb: "Graceville", state: "QLD", postcode: "4075" },
  { suburb: "Sherwood", state: "QLD", postcode: "4075" },
  { suburb: "Corinda", state: "QLD", postcode: "4075" },
  { suburb: "Oxley", state: "QLD", postcode: "4075" },
  { suburb: "Darra", state: "QLD", postcode: "4076" },
  { suburb: "Wacol", state: "QLD", postcode: "4076" },
  { suburb: "Jindalee", state: "QLD", postcode: "4074" },
  { suburb: "Mount Ommaney", state: "QLD", postcode: "4074" },
  { suburb: "Westlake", state: "QLD", postcode: "4074" },
  { suburb: "Middle Park", state: "QLD", postcode: "4074" },
  { suburb: "Jamboree Heights", state: "QLD", postcode: "4074" },
  { suburb: "Windsor", state: "QLD", postcode: "4030" },
  { suburb: "Wilston", state: "QLD", postcode: "4051" },
  { suburb: "Grange", state: "QLD", postcode: "4051" },
  { suburb: "Alderley", state: "QLD", postcode: "4051" },
  { suburb: "Enoggera", state: "QLD", postcode: "4051" },
  { suburb: "Newmarket", state: "QLD", postcode: "4051" },
  { suburb: "Stafford", state: "QLD", postcode: "4053" },
  { suburb: "Stafford Heights", state: "QLD", postcode: "4053" },
  { suburb: "Everton Park", state: "QLD", postcode: "4053" },
  { suburb: "Everton Hills", state: "QLD", postcode: "4053" },
  { suburb: "Mitchelton", state: "QLD", postcode: "4053" },
  { suburb: "Gaythorne", state: "QLD", postcode: "4051" },
  { suburb: "Keperra", state: "QLD", postcode: "4054" },
  { suburb: "Ferny Grove", state: "QLD", postcode: "4055" },
  { suburb: "Ferny Hills", state: "QLD", postcode: "4055" },
  { suburb: "Albion", state: "QLD", postcode: "4010" },
  { suburb: "Lutwyche", state: "QLD", postcode: "4030" },
  { suburb: "Wooloowin", state: "QLD", postcode: "4030" },
  { suburb: "Clayfield", state: "QLD", postcode: "4011" },
  { suburb: "Hendra", state: "QLD", postcode: "4011" },
  { suburb: "Ascot", state: "QLD", postcode: "4007" },
  { suburb: "Hamilton", state: "QLD", postcode: "4007" },
  { suburb: "Eagle Farm", state: "QLD", postcode: "4009" },
  { suburb: "Pinkenba", state: "QLD", postcode: "4008" },
  { suburb: "Nundah", state: "QLD", postcode: "4012" },
  { suburb: "Northgate", state: "QLD", postcode: "4013" },
  { suburb: "Virginia", state: "QLD", postcode: "4014" },
  { suburb: "Banyo", state: "QLD", postcode: "4014" },
  { suburb: "Nudgee", state: "QLD", postcode: "4014" },
  { suburb: "Nudgee Beach", state: "QLD", postcode: "4014" },
  { suburb: "Kedron", state: "QLD", postcode: "4031" },
  { suburb: "Chermside", state: "QLD", postcode: "4032" },
  { suburb: "Chermside West", state: "QLD", postcode: "4032" },
  { suburb: "Aspley", state: "QLD", postcode: "4034" },
  { suburb: "Carseldine", state: "QLD", postcode: "4034" },
  { suburb: "Geebung", state: "QLD", postcode: "4034" },
  { suburb: "Zillmere", state: "QLD", postcode: "4034" },
  { suburb: "Boondall", state: "QLD", postcode: "4034" },
  { suburb: "Taigum", state: "QLD", postcode: "4018" },
  { suburb: "Fitzgibbon", state: "QLD", postcode: "4018" },
  { suburb: "Bracken Ridge", state: "QLD", postcode: "4017" },
  { suburb: "Sandgate", state: "QLD", postcode: "4017" },
  { suburb: "Brighton", state: "QLD", postcode: "4017" },
  { suburb: "Shorncliffe", state: "QLD", postcode: "4017" },
  { suburb: "Deagon", state: "QLD", postcode: "4017" },
  { suburb: "Bridgeman Downs", state: "QLD", postcode: "4035" },
  { suburb: "Albany Creek", state: "QLD", postcode: "4035" },
  { suburb: "Eatons Hill", state: "QLD", postcode: "4037" },
  { suburb: "Warner", state: "QLD", postcode: "4500" },
  { suburb: "Brendale", state: "QLD", postcode: "4500" },
  { suburb: "Strathpine", state: "QLD", postcode: "4500" },
  { suburb: "Bald Hills", state: "QLD", postcode: "4036" },
  { suburb: "Lawnton", state: "QLD", postcode: "4501" },
  { suburb: "Petrie", state: "QLD", postcode: "4502" },
  { suburb: "Kallangur", state: "QLD", postcode: "4503" },
  { suburb: "Murrumba Downs", state: "QLD", postcode: "4503" },
  { suburb: "Griffin", state: "QLD", postcode: "4503" },
  { suburb: "Mango Hill", state: "QLD", postcode: "4509" },
  { suburb: "North Lakes", state: "QLD", postcode: "4509" },
  { suburb: "Rothwell", state: "QLD", postcode: "4022" },
  { suburb: "Kippa-Ring", state: "QLD", postcode: "4021" },
  { suburb: "Clontarf", state: "QLD", postcode: "4019" },
  { suburb: "Margate", state: "QLD", postcode: "4019" },
  { suburb: "Woody Point", state: "QLD", postcode: "4019" },
  { suburb: "Redcliffe", state: "QLD", postcode: "4020" },
  { suburb: "Scarborough", state: "QLD", postcode: "4020" },
  { suburb: "Newport", state: "QLD", postcode: "4020" },
  { suburb: "Deception Bay", state: "QLD", postcode: "4508" },
  { suburb: "Narangba", state: "QLD", postcode: "4504" },
  { suburb: "Burpengary", state: "QLD", postcode: "4505" },
  { suburb: "Burpengary East", state: "QLD", postcode: "4505" },
  { suburb: "Morayfield", state: "QLD", postcode: "4506" },
  { suburb: "Caboolture", state: "QLD", postcode: "4510" },
  { suburb: "Caboolture South", state: "QLD", postcode: "4510" },
  { suburb: "Bribie Island", state: "QLD", postcode: "4507" },
  { suburb: "Bongaree", state: "QLD", postcode: "4507" },
  { suburb: "Bellara", state: "QLD", postcode: "4507" },

  // Redland City
  { suburb: "Capalaba", state: "QLD", postcode: "4157" },
  { suburb: "Birkdale", state: "QLD", postcode: "4159" },
  { suburb: "Wellington Point", state: "QLD", postcode: "4160" },
  { suburb: "Ormiston", state: "QLD", postcode: "4160" },
  { suburb: "Alexandra Hills", state: "QLD", postcode: "4161" },
  { suburb: "Cleveland", state: "QLD", postcode: "4163" },
  { suburb: "Thornlands", state: "QLD", postcode: "4164" },
  { suburb: "Victoria Point", state: "QLD", postcode: "4165" },
  { suburb: "Redland Bay", state: "QLD", postcode: "4165" },
  { suburb: "Mount Cotton", state: "QLD", postcode: "4165" },

  // Logan City
  { suburb: "Logan Central", state: "QLD", postcode: "4114" },
  { suburb: "Woodridge", state: "QLD", postcode: "4114" },
  { suburb: "Kingston", state: "QLD", postcode: "4114" },
  { suburb: "Underwood", state: "QLD", postcode: "4119" },
  { suburb: "Springwood", state: "QLD", postcode: "4127" },
  { suburb: "Slacks Creek", state: "QLD", postcode: "4127" },
  { suburb: "Daisy Hill", state: "QLD", postcode: "4127" },
  { suburb: "Priestdale", state: "QLD", postcode: "4127" },
  { suburb: "Rochedale South", state: "QLD", postcode: "4123" },
  { suburb: "Rochedale", state: "QLD", postcode: "4123" },
  { suburb: "Shailer Park", state: "QLD", postcode: "4128" },
  { suburb: "Tanah Merah", state: "QLD", postcode: "4128" },
  { suburb: "Loganholme", state: "QLD", postcode: "4129" },
  { suburb: "Carbrook", state: "QLD", postcode: "4130" },
  { suburb: "Cornubia", state: "QLD", postcode: "4130" },
  { suburb: "Meadowbrook", state: "QLD", postcode: "4131" },
  { suburb: "Loganlea", state: "QLD", postcode: "4131" },
  { suburb: "Waterford", state: "QLD", postcode: "4133" },
  { suburb: "Waterford West", state: "QLD", postcode: "4133" },
  { suburb: "Marsden", state: "QLD", postcode: "4132" },
  { suburb: "Crestmead", state: "QLD", postcode: "4132" },
  { suburb: "Berrinba", state: "QLD", postcode: "4117" },
  { suburb: "Browns Plains", state: "QLD", postcode: "4118" },
  { suburb: "Regents Park", state: "QLD", postcode: "4118" },
  { suburb: "Heritage Park", state: "QLD", postcode: "4118" },
  { suburb: "Hillcrest", state: "QLD", postcode: "4118" },
  { suburb: "Forestdale", state: "QLD", postcode: "4118" },
  { suburb: "Park Ridge", state: "QLD", postcode: "4125" },
  { suburb: "Park Ridge South", state: "QLD", postcode: "4125" },
  { suburb: "Boronia Heights", state: "QLD", postcode: "4124" },
  { suburb: "Greenbank", state: "QLD", postcode: "4124" },
  { suburb: "New Beith", state: "QLD", postcode: "4124" },
  { suburb: "Munruben", state: "QLD", postcode: "4125" },
  { suburb: "North Maclean", state: "QLD", postcode: "4280" },
  { suburb: "South Maclean", state: "QLD", postcode: "4280" },
  { suburb: "Jimboomba", state: "QLD", postcode: "4280" },
  { suburb: "Flagstone", state: "QLD", postcode: "4280" },
  { suburb: "Yarrabilba", state: "QLD", postcode: "4207" },
  { suburb: "Logan Village", state: "QLD", postcode: "4207" },
  { suburb: "Buccan", state: "QLD", postcode: "4207" },
  { suburb: "Beenleigh", state: "QLD", postcode: "4207" },
  { suburb: "Eagleby", state: "QLD", postcode: "4207" },
  { suburb: "Mount Warren Park", state: "QLD", postcode: "4207" },
  { suburb: "Holmview", state: "QLD", postcode: "4207" },
  { suburb: "Edens Landing", state: "QLD", postcode: "4207" },
  { suburb: "Bethania", state: "QLD", postcode: "4205" },

  // Ipswich & Western Corridor
  { suburb: "Ipswich", state: "QLD", postcode: "4305" },
  { suburb: "North Ipswich", state: "QLD", postcode: "4305" },
  { suburb: "East Ipswich", state: "QLD", postcode: "4305" },
  { suburb: "West Ipswich", state: "QLD", postcode: "4305" },
  { suburb: "Brassall", state: "QLD", postcode: "4305" },
  { suburb: "Woodend", state: "QLD", postcode: "4305" },
  { suburb: "Sadliers Crossing", state: "QLD", postcode: "4305" },
  { suburb: "Coalfalls", state: "QLD", postcode: "4305" },
  { suburb: "Booval", state: "QLD", postcode: "4304" },
  { suburb: "North Booval", state: "QLD", postcode: "4304" },
  { suburb: "Silkstone", state: "QLD", postcode: "4304" },
  { suburb: "Bundamba", state: "QLD", postcode: "4304" },
  { suburb: "Blackstone", state: "QLD", postcode: "4304" },
  { suburb: "Ebbw Vale", state: "QLD", postcode: "4304" },
  { suburb: "Dinmore", state: "QLD", postcode: "4303" },
  { suburb: "Riverview", state: "QLD", postcode: "4303" },
  { suburb: "Redbank", state: "QLD", postcode: "4301" },
  { suburb: "Collingwood Park", state: "QLD", postcode: "4301" },
  { suburb: "Redbank Plains", state: "QLD", postcode: "4301" },
  { suburb: "Bellbird Park", state: "QLD", postcode: "4300" },
  { suburb: "Goodna", state: "QLD", postcode: "4300" },
  { suburb: "Gailes", state: "QLD", postcode: "4300" },
  { suburb: "Camira", state: "QLD", postcode: "4300" },
  { suburb: "Springfield", state: "QLD", postcode: "4300" },
  { suburb: "Springfield Lakes", state: "QLD", postcode: "4300" },
  { suburb: "Springfield Central", state: "QLD", postcode: "4300" },
  { suburb: "Brookwater", state: "QLD", postcode: "4300" },
  { suburb: "Augustine Heights", state: "QLD", postcode: "4300" },
  { suburb: "Ripley", state: "QLD", postcode: "4306" },
  { suburb: "South Ripley", state: "QLD", postcode: "4306" },
  { suburb: "Deebing Heights", state: "QLD", postcode: "4306" },
  { suburb: "Yamanto", state: "QLD", postcode: "4305" },
  { suburb: "Raceview", state: "QLD", postcode: "4305" },
  { suburb: "Flinders View", state: "QLD", postcode: "4305" },
  { suburb: "Churchill", state: "QLD", postcode: "4305" },
  { suburb: "Karalee", state: "QLD", postcode: "4306" },
  { suburb: "Karana Downs", state: "QLD", postcode: "4306" },
  { suburb: "Mount Crosby", state: "QLD", postcode: "4306" },
  { suburb: "Anstead", state: "QLD", postcode: "4070" },
  { suburb: "Bellbowrie", state: "QLD", postcode: "4070" },
  { suburb: "Moggill", state: "QLD", postcode: "4070" },
  { suburb: "Pullenvale", state: "QLD", postcode: "4069" },
  { suburb: "Kenmore", state: "QLD", postcode: "4069" },
  { suburb: "Kenmore Hills", state: "QLD", postcode: "4069" },
  { suburb: "Chapel Hill", state: "QLD", postcode: "4069" },

  // Gold Coast
  { suburb: "Yatala", state: "QLD", postcode: "4207" },
  { suburb: "Stapylton", state: "QLD", postcode: "4207" },
  { suburb: "Ormeau", state: "QLD", postcode: "4208" },
  { suburb: "Ormeau Hills", state: "QLD", postcode: "4208" },
  { suburb: "Kingsholme", state: "QLD", postcode: "4208" },
  { suburb: "Norwell", state: "QLD", postcode: "4208" },
  { suburb: "Pimpama", state: "QLD", postcode: "4209" },
  { suburb: "Coomera", state: "QLD", postcode: "4209" },
  { suburb: "Upper Coomera", state: "QLD", postcode: "4209" },
  { suburb: "Willow Vale", state: "QLD", postcode: "4209" },
  { suburb: "Helensvale", state: "QLD", postcode: "4212" },
  { suburb: "Hope Island", state: "QLD", postcode: "4212" },
  { suburb: "Sanctuary Cove", state: "QLD", postcode: "4212" },
  { suburb: "Oxenford", state: "QLD", postcode: "4210" },
  { suburb: "Maudsland", state: "QLD", postcode: "4210" },
  { suburb: "Guanaba", state: "QLD", postcode: "4210" },
  { suburb: "Pacific Pines", state: "QLD", postcode: "4211" },
  { suburb: "Gaven", state: "QLD", postcode: "4211" },
  { suburb: "Arundel", state: "QLD", postcode: "4214" },
  { suburb: "Parkwood", state: "QLD", postcode: "4214" },
  { suburb: "Coombabah", state: "QLD", postcode: "4216" },
  { suburb: "Paradise Point", state: "QLD", postcode: "4216" },
  { suburb: "Runaway Bay", state: "QLD", postcode: "4216" },
  { suburb: "Hollywell", state: "QLD", postcode: "4216" },
  { suburb: "Biggera Waters", state: "QLD", postcode: "4216" },
  { suburb: "Labrador", state: "QLD", postcode: "4215" },
  { suburb: "Southport", state: "QLD", postcode: "4215" },
  { suburb: "Main Beach", state: "QLD", postcode: "4217" },
  { suburb: "Surfers Paradise", state: "QLD", postcode: "4217" },
  { suburb: "Bundall", state: "QLD", postcode: "4217" },
  { suburb: "Chevron Island", state: "QLD", postcode: "4217" },
  { suburb: "Isle of Capri", state: "QLD", postcode: "4217" },
  { suburb: "Benowa", state: "QLD", postcode: "4217" },
  { suburb: "Ashmore", state: "QLD", postcode: "4214" },
  { suburb: "Molendinar", state: "QLD", postcode: "4214" },
  { suburb: "Nerang", state: "QLD", postcode: "4211" },
  { suburb: "Highland Park", state: "QLD", postcode: "4211" },
  { suburb: "Carrara", state: "QLD", postcode: "4211" },
  { suburb: "Broadbeach", state: "QLD", postcode: "4218" },
  { suburb: "Broadbeach Waters", state: "QLD", postcode: "4218" },
  { suburb: "Mermaid Beach", state: "QLD", postcode: "4218" },
  { suburb: "Mermaid Waters", state: "QLD", postcode: "4218" },
  { suburb: "Miami", state: "QLD", postcode: "4220" },
  { suburb: "Burleigh Heads", state: "QLD", postcode: "4220" },
  { suburb: "Burleigh Waters", state: "QLD", postcode: "4220" },
  { suburb: "Palm Beach", state: "QLD", postcode: "4221" },
  { suburb: "Elanora", state: "QLD", postcode: "4221" },
  { suburb: "Currumbin", state: "QLD", postcode: "4223" },
  { suburb: "Currumbin Waters", state: "QLD", postcode: "4223" },
  { suburb: "Currumbin Valley", state: "QLD", postcode: "4223" },
  { suburb: "Tugun", state: "QLD", postcode: "4224" },
  { suburb: "Bilinga", state: "QLD", postcode: "4225" },
  { suburb: "Coolangatta", state: "QLD", postcode: "4225" },
  { suburb: "Kirra", state: "QLD", postcode: "4225" },
  { suburb: "Rainbow Bay", state: "QLD", postcode: "4225" },
  { suburb: "Tweed Heads", state: "NSW", postcode: "2485" },
  { suburb: "Robina", state: "QLD", postcode: "4226" },
  { suburb: "Clear Island Waters", state: "QLD", postcode: "4226" },
  { suburb: "Varsity Lakes", state: "QLD", postcode: "4227" },
  { suburb: "Reedy Creek", state: "QLD", postcode: "4227" },
  { suburb: "Mudgeeraba", state: "QLD", postcode: "4213" },
  { suburb: "Tallai", state: "QLD", postcode: "4213" },
  { suburb: "Worongary", state: "QLD", postcode: "4213" },
  { suburb: "Bonogin", state: "QLD", postcode: "4213" },
  { suburb: "Tallebudgera", state: "QLD", postcode: "4228" },
  { suburb: "Tallebudgera Valley", state: "QLD", postcode: "4228" },

  // Sunshine Coast
  { suburb: "Caloundra", state: "QLD", postcode: "4551" },
  { suburb: "Caloundra West", state: "QLD", postcode: "4551" },
  { suburb: "Pelican Waters", state: "QLD", postcode: "4551" },
  { suburb: "Golden Beach", state: "QLD", postcode: "4551" },
  { suburb: "Kings Beach", state: "QLD", postcode: "4551" },
  { suburb: "Moffat Beach", state: "QLD", postcode: "4551" },
  { suburb: "Shelly Beach", state: "QLD", postcode: "4551" },
  { suburb: "Dicky Beach", state: "QLD", postcode: "4551" },
  { suburb: "Currimundi", state: "QLD", postcode: "4551" },
  { suburb: "Aroona", state: "QLD", postcode: "4551" },
  { suburb: "Little Mountain", state: "QLD", postcode: "4551" },
  { suburb: "Bells Creek", state: "QLD", postcode: "4551" },
  { suburb: "Aura", state: "QLD", postcode: "4551" },
  { suburb: "Baringa", state: "QLD", postcode: "4551" },
  { suburb: "Nirimba", state: "QLD", postcode: "4551" },
  { suburb: "Kawana Waters", state: "QLD", postcode: "4575" },
  { suburb: "Buddina", state: "QLD", postcode: "4575" },
  { suburb: "Minyama", state: "QLD", postcode: "4575" },
  { suburb: "Parrearra", state: "QLD", postcode: "4575" },
  { suburb: "Warana", state: "QLD", postcode: "4575" },
  { suburb: "Bokarina", state: "QLD", postcode: "4575" },
  { suburb: "Birtinya", state: "QLD", postcode: "4575" },
  { suburb: "Wurtulla", state: "QLD", postcode: "4575" },
  { suburb: "Mooloolaba", state: "QLD", postcode: "4557" },
  { suburb: "Mountain Creek", state: "QLD", postcode: "4557" },
  { suburb: "Alexandra Headland", state: "QLD", postcode: "4572" },
  { suburb: "Maroochydore", state: "QLD", postcode: "4558" },
  { suburb: "Cotton Tree", state: "QLD", postcode: "4558" },
  { suburb: "Sunshine Plaza", state: "QLD", postcode: "4558" },
  { suburb: "Kuluin", state: "QLD", postcode: "4558" },
  { suburb: "Buderim", state: "QLD", postcode: "4556" },
  { suburb: "Sippy Downs", state: "QLD", postcode: "4556" },
  { suburb: "Forest Glen", state: "QLD", postcode: "4556" },
  { suburb: "Mons", state: "QLD", postcode: "4556" },
  { suburb: "Kunda Park", state: "QLD", postcode: "4556" },
  { suburb: "Bli Bli", state: "QLD", postcode: "4560" },
  { suburb: "Nambour", state: "QLD", postcode: "4560" },
  { suburb: "Burnside", state: "QLD", postcode: "4560" },
  { suburb: "Woombye", state: "QLD", postcode: "4559" },
  { suburb: "Palmwoods", state: "QLD", postcode: "4555" },
  { suburb: "Marcoola", state: "QLD", postcode: "4564" },
  { suburb: "Mudjimba", state: "QLD", postcode: "4564" },
  { suburb: "Pacific Paradise", state: "QLD", postcode: "4564" },
  { suburb: "Twin Waters", state: "QLD", postcode: "4564" },
  { suburb: "Mount Coolum", state: "QLD", postcode: "4573" },
  { suburb: "Coolum Beach", state: "QLD", postcode: "4573" },
  { suburb: "Yaroomba", state: "QLD", postcode: "4573" },
  { suburb: "Peregian Beach", state: "QLD", postcode: "4573" },
  { suburb: "Peregian Springs", state: "QLD", postcode: "4573" },
  { suburb: "Marcus Beach", state: "QLD", postcode: "4573" },
  { suburb: "Castaways Beach", state: "QLD", postcode: "4567" },
  { suburb: "Sunrise Beach", state: "QLD", postcode: "4567" },
  { suburb: "Sunshine Beach", state: "QLD", postcode: "4567" },
  { suburb: "Noosa Heads", state: "QLD", postcode: "4567" },
  { suburb: "Noosaville", state: "QLD", postcode: "4566" },
  { suburb: "Tewantin", state: "QLD", postcode: "4565" },
  { suburb: "Doonan", state: "QLD", postcode: "4562" },
  { suburb: "Eumundi", state: "QLD", postcode: "4562" },
  { suburb: "Cooroy", state: "QLD", postcode: "4563" },

  // Toowoomba & Darling Downs
  { suburb: "Toowoomba", state: "QLD", postcode: "4350" },
  { suburb: "East Toowoomba", state: "QLD", postcode: "4350" },
  { suburb: "South Toowoomba", state: "QLD", postcode: "4350" },
  { suburb: "North Toowoomba", state: "QLD", postcode: "4350" },
  { suburb: "Rangeville", state: "QLD", postcode: "4350" },
  { suburb: "Middle Ridge", state: "QLD", postcode: "4350" },
  { suburb: "Kearneys Spring", state: "QLD", postcode: "4350" },
  { suburb: "Darling Heights", state: "QLD", postcode: "4350" },
  { suburb: "Centenary Heights", state: "QLD", postcode: "4350" },
  { suburb: "Wilsonton", state: "QLD", postcode: "4350" },
  { suburb: "Wilsonton Heights", state: "QLD", postcode: "4350" },
  { suburb: "Newtown", state: "QLD", postcode: "4350" },
  { suburb: "Harristown", state: "QLD", postcode: "4350" },
  { suburb: "Drayton", state: "QLD", postcode: "4350" },
  { suburb: "Glenvale", state: "QLD", postcode: "4350" },
  { suburb: "Cranley", state: "QLD", postcode: "4350" },
  { suburb: "Rockville", state: "QLD", postcode: "4350" },
  { suburb: "Mount Lofty", state: "QLD", postcode: "4350" },
  { suburb: "Highfields", state: "QLD", postcode: "4352" },
  { suburb: "Gatton", state: "QLD", postcode: "4343" },
  { suburb: "Plainland", state: "QLD", postcode: "4341" },
  { suburb: "Laidley", state: "QLD", postcode: "4341" },

  // Regional Queensland Cities
  { suburb: "Gold Coast", state: "QLD", postcode: "4217" },
  { suburb: "Sunshine Coast", state: "QLD", postcode: "4558" },
  { suburb: "Cairns", state: "QLD", postcode: "4870" },
  { suburb: "Cairns City", state: "QLD", postcode: "4870" },
  { suburb: "Cairns North", state: "QLD", postcode: "4870" },
  { suburb: "Townsville", state: "QLD", postcode: "4810" },
  { suburb: "Townsville City", state: "QLD", postcode: "4810" },
  { suburb: "Mackay", state: "QLD", postcode: "4740" },
  { suburb: "Rockhampton", state: "QLD", postcode: "4700" },
  { suburb: "Bundaberg", state: "QLD", postcode: "4670" },
  { suburb: "Gladstone", state: "QLD", postcode: "4680" },
  { suburb: "Hervey Bay", state: "QLD", postcode: "4655" },
  { suburb: "Maryborough", state: "QLD", postcode: "4650" },
  { suburb: "Gympie", state: "QLD", postcode: "4570" },
  { suburb: "Mount Isa", state: "QLD", postcode: "4825" },

  // Major Interstate Hubs
  { suburb: "Sydney", state: "NSW", postcode: "2000" },
  { suburb: "Melbourne", state: "VIC", postcode: "3000" },
  { suburb: "Canberra", state: "ACT", postcode: "2600" },
  { suburb: "Adelaide", state: "SA", postcode: "5000" },
  { suburb: "Perth", state: "WA", postcode: "6000" },
  { suburb: "Darwin", state: "NT", postcode: "0800" },
  { suburb: "Hobart", state: "TAS", postcode: "7000" }
];

/**
 * Normalizes string for fuzzy comparison
 */
function normalize(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Finds matching suburb and returns postal code
 */
export function findLocalSuburb(suburbName: string): SuburbData | undefined {
  const cleanInput = normalize(suburbName);
  if (!cleanInput) return undefined;

  // Exact match first
  const exact = QUEENSLAND_SUBURBS.find(s => normalize(s.suburb) === cleanInput);
  if (exact) return exact;

  // Prefix match
  const prefix = QUEENSLAND_SUBURBS.find(s => normalize(s.suburb).startsWith(cleanInput));
  if (prefix) return prefix;

  // Substring match
  return QUEENSLAND_SUBURBS.find(s => normalize(s.suburb).includes(cleanInput));
}

/**
 * Searches local database for autocomplete suggestions
 */
export function searchSuburbs(query: string, limit = 8): SuburbData[] {
  const clean = normalize(query);
  if (!clean || clean.length < 2) return [];

  // Check if searching by postcode directly (numeric)
  if (/^\d+$/.test(query.trim())) {
    return QUEENSLAND_SUBURBS
      .filter(s => s.postcode.startsWith(query.trim()))
      .slice(0, limit);
  }

  // Exact starts-with first, then includes
  const startsWith = QUEENSLAND_SUBURBS.filter(s => normalize(s.suburb).startsWith(clean));
  const includes = QUEENSLAND_SUBURBS.filter(s => !normalize(s.suburb).startsWith(clean) && normalize(s.suburb).includes(clean));

  return [...startsWith, ...includes].slice(0, limit);
}

/**
 * Formats suburb, state, and postcode nicely
 */
export function formatLocation(suburb: string, state = "QLD", postcode?: string): string {
  if (postcode) {
    return `${suburb}, ${state} ${postcode}`.trim();
  }
  const match = findLocalSuburb(suburb);
  if (match) {
    return `${match.suburb}, ${match.state} ${match.postcode}`;
  }
  return `${suburb}, ${state}`.trim();
}
